## 快速创建数组

In [1]:
import numpy as np

随机创建一个数组

`randn(10)` 创建一个长度为10，里面数值符合正态分布的数组,数值为float

In [2]:
np.random.randn(10)

array([-0.62618368,  0.54069717,  1.10779989, -1.83657213,  1.72928099,
        0.21080405, -0.75527942, -0.28579821,  1.35614876,  0.97041025])

`ranint` 会返回0 -到- 给定参数数字范围之内的一个随机整数

- `size` 指定创建的是数组的shape。将创建指定shape，并用随机数填充

In [3]:
np.random.randint(10, size=(2,3))

array([[0, 6, 0],
       [5, 8, 1]])

一维数组 `size` 为 20

In [4]:
np.random.randint(10, size=20)

array([4, 7, 3, 1, 6, 7, 4, 8, 6, 8, 0, 1, 8, 8, 4, 2, 3, 3, 0, 7])

通过reshape方法将一维数组改为多维数组

In [5]:
np.random.randint(10, size=20).reshape(4,5)

array([[9, 6, 0, 2, 3],
       [6, 6, 6, 7, 9],
       [6, 1, 6, 6, 7],
       [8, 6, 2, 0, 3]])

## 数组运算

In [6]:
a = np.random.randint(10, size=20).reshape(4,5)

In [7]:
b = np.random.randint(10, size=20).reshape(4,5)

In [8]:
a

array([[4, 8, 5, 6, 7],
       [9, 8, 7, 8, 2],
       [6, 4, 4, 9, 9],
       [0, 0, 0, 0, 6]])

In [9]:
b

array([[8, 0, 9, 8, 8],
       [2, 3, 0, 9, 6],
       [2, 4, 1, 4, 8],
       [4, 8, 7, 4, 8]])

- 数组的加法是对应位置元素的算数和。
- 数组的减法是对应位置元素相减得到的值。

In [10]:
a + b

array([[12,  8, 14, 14, 15],
       [11, 11,  7, 17,  8],
       [ 8,  8,  5, 13, 17],
       [ 4,  8,  7,  4, 14]])

In [11]:
a - b

array([[-4,  8, -4, -2, -1],
       [ 7,  5,  7, -1, -4],
       [ 4,  0,  3,  5,  1],
       [-4, -8, -7, -4, -2]])

乘法也是对应位置元素的乘积

In [12]:
a * b

array([[32,  0, 45, 48, 56],
       [18, 24,  0, 72, 12],
       [12, 16,  4, 36, 72],
       [ 0,  0,  0,  0, 48]])

除法会报warning，因为有的除数，值为0.

- 如果遇到除0，会给一个无限大的标志inf

In [13]:
a / b

D:\softEnvDown\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ 0.5       ,         inf,  0.55555556,  0.75      ,  0.875     ],
       [ 4.5       ,  2.66666667,         inf,  0.88888889,  0.33333333],
       [ 3.        ,  1.        ,  4.        ,  2.25      ,  1.125     ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.75      ]])

## 矩阵

创建二维矩阵

In [14]:
np.mat([[1,2,3],[4,5,6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

矩阵和数组之间可以进行相互转化

直接传入数组a，即可根据数组创建对应的矩阵

In [15]:
np.mat(a)

matrix([[4, 8, 5, 6, 7],
        [9, 8, 7, 8, 2],
        [6, 4, 4, 9, 9],
        [0, 0, 0, 0, 6]])

## 矩阵运算

In [16]:
A = np.mat(a)

In [17]:
B = np.mat(b)

In [18]:
A

matrix([[4, 8, 5, 6, 7],
        [9, 8, 7, 8, 2],
        [6, 4, 4, 9, 9],
        [0, 0, 0, 0, 6]])

In [19]:
B

matrix([[8, 0, 9, 8, 8],
        [2, 3, 0, 9, 6],
        [2, 4, 1, 4, 8],
        [4, 8, 7, 4, 8]])

矩阵的加法运算和减法运算仍然是通过对应位置元素的加减产生新的矩阵。与数组相同。

In [20]:
A + B

matrix([[12,  8, 14, 14, 15],
        [11, 11,  7, 17,  8],
        [ 8,  8,  5, 13, 17],
        [ 4,  8,  7,  4, 14]])

In [21]:
A - B

matrix([[-4,  8, -4, -2, -1],
        [ 7,  5,  7, -1, -4],
        [ 4,  0,  3,  5,  1],
        [-4, -8, -7, -4, -2]])

此时如果直接运行`A*B` 那么会报错。因为矩阵相乘，A的行数必须等于B的列数。

In [22]:
# A * B

In [23]:
B_reshape = B.reshape(5,4)

In [24]:
B_reshape

matrix([[8, 0, 9, 8],
        [8, 2, 3, 0],
        [9, 6, 2, 4],
        [1, 4, 8, 4],
        [8, 7, 4, 8]])

In [25]:
A *  B.reshape(5,4)

matrix([[203, 119, 146, 132],
        [223, 104, 191, 148],
        [197, 131, 182, 172],
        [ 48,  42,  24,  48]])

## Array常用函数

- unique 返回数组中那些值是唯一的
- sum 对于数组中每一列元素进行求和

In [26]:
a = np.random.randint(10, size=20).reshape(4,5)

In [27]:
np.unique(a)

array([0, 1, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a

array([[0, 3, 4, 9, 6],
       [0, 3, 1, 3, 4],
       [7, 5, 3, 8, 0],
       [5, 3, 6, 1, 7]])

In [29]:
sum(a)

array([12, 14, 14, 21, 17])

对于指定行进行求和: 对于第一行进行求和

In [30]:
sum(a[0])

22

对于指定列进行求和: 下面是对第一列进行求和

In [31]:
sum(a[:,0])

12

max 函数 查看数组中的最大值

In [32]:
a.max()

9

求第0行的最大值

In [33]:
max(a[0])

9

求第1列的最大值

In [34]:
max(a[:,1])

5

In [35]:
a[:,1].max()

5