### 数组的创建和访问

In [1]:
import numpy as np

# create from python list
list_1 = [1,2,3,4]
print(list_1)

# 通过 `np.array` 将我们的list作为输入参数创建一维数组。
array_1 = np.array(list_1)
print(array_1)

[1, 2, 3, 4]
[1 2 3 4]


In [2]:
list_2 = [5,6,7,8]
# 通过创建一个将list_1,list_2作为元素的list来实现创建二维数组（矩阵）。
array_2 = np.array([list_1,list_2])

print(array_2)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
'''
下面代码演示如何获取一些数组的属性
- shape 两行四列
- size  返回整个数组中元素的个数
- dtype 返回数组中元素的数据类型
'''
print(array_2.shape)
print(array_2.size)
print(array_2.dtype)

(2, 4)
8
int64


In [4]:
# 数据类型不一致时会进行隐式转换，取精确度最高的位
array_3 = np.array([[1.0,2,3],[4.0,5,6]])

print(array_3.dtype)

float64


In [5]:
# 下面代码通过arange 来创建Numpy数组: 可指定起始点，终点，步长
array_4 = np.arange(1,10,2)

print(array_4)

[1 3 5 7 9]


In [6]:
# 零矩阵
array_5 = np.zeros(5)
print(array_5) 

# 传入指定shape的list形状返回指定shape的矩阵
array_6 = np.zeros([2,3])
print(array_6)
print("*"*10)

# 通过 np.eye 产生单位矩阵
eye = np.eye(5)
print(eye)
print(eye.dtype)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
**********
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
float64


>可以看到零矩阵和单位矩阵，都是浮点类型的。

In [7]:
a = np.arange(1,10)
print(a)
# 访问数组的元素
print(a[2])
# 类似于python list的切片
print(a[1:5])

[1 2 3 4 5 6 7 8 9]
3
[2 3 4 5]


In [8]:
# (2,3)矩阵
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [9]:
# 访问二维数组中的元素，指定你要访问第几行第几列,索引从0开始
print(b[1][2])
print(b[1,2])

6
6


In [10]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

'''
对于二维数组的一个切片：
- 前面 `:2` 代表我们需要的行的范围(我们从第0行到第二行。也就是0 1两行)
- 后面 `1:` 代表列数，从第一列开始到最后。那么第0列就没了。
'''
print("*"*10)
print(c[:2,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
**********
[[2 3]
 [5 6]]
