Array的`input`和`output`类似于我们在python中去序列化一个对象

`pickle` 进行序列化

In [1]:
import pickle
import numpy as np

## 使用传统的pickle序列化numpy array

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

打开一个文件: 以二进制方式打开，因为序列化后的对象数据是二进制。

In [4]:
f = open('x.pkl', 'wb')

dump可以将x对象，dump进f中

In [5]:
pickle.dump(x,f)

In [6]:
!ls

Array鐨刬nput鍜宱utput.ipynb
HelloWorld.ipynb
ReadMe.md
one_array.npy
two_array.npz
x.pkl
鏁扮粍涓庣煩闃佃繍绠�.ipynb
鏁扮粍绠�浠�.ipynb


In [7]:
f = open('x.pkl','rb')

In [8]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Numpy提供了更简单的方法 save load

In [9]:
np.save("one_array",x)

In [10]:
!ls

Array鐨刬nput鍜宱utput.ipynb
HelloWorld.ipynb
ReadMe.md
one_array.npy
two_array.npz
x.pkl
鏁扮粍涓庣煩闃佃繍绠�.ipynb
鏁扮粍绠�浠�.ipynb


In [11]:
np.load("one_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
y = np.arange(20)

In [13]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

有多个数组想要序列化,使用 `savez` 进行压缩

In [14]:
y = np.savez('two_array.npz',a=x,b=y)

In [15]:
!ls

Array鐨刬nput鍜宱utput.ipynb
HelloWorld.ipynb
ReadMe.md
one_array.npy
two_array.npz
x.pkl
鏁扮粍涓庣煩闃佃繍绠�.ipynb
鏁扮粍绠�浠�.ipynb


In [16]:
z = np.load('two_array.npz')

In [17]:
z['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
z['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

官方文档地址: https://docs.scipy.org/doc/numpy-dev/dev/